# Generated by Django 4.1 on 2022-10-05 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appUsuario', '0005_alter_avatar_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenArticulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenesArticulos')),
                ('articulo', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='appUsuario.articulo')),
            ],
        ),
    ]
