# Generated by Django 4.1 on 2022-10-05 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appUsuario', '0006_imagenarticulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenesArticulos'),
        ),
    ]
